default:
    extension: .rasi
    output: themes

colors:
    extension: .rasi
    output: colors

colors_minial:
    extension: .rasi
    output: colors

old:
    extension: .config
    output: themes
