default:
    extension: .config.py
    output: themes/default

minimal:
    extension: .config.py
    output: themes/minimal

minimal:
    extension: .config.py
    output: themes/minimal_transparent
