customCommands:
  - key: "<c-a>"
    context: "commits"
    command: "gh run list --commit {{.SelectedLocalCommit.Hash}}"
    stream: true
    description: "Show commit's gh workflow run"
  - key: "<c-a>"
    context: "global"
    command: "gh run watch"
    description: "Watch gh workflow run"
    subprocess: true
  - key: "<c-t>"
    context: "global"
    command: "git push --tags"
    description: "Push tags"
    stream: true
  - key: "<c-u>"
    context: "localBranches"
    command: "gh pr create --head {{.SelectedLocalBranch.Name}}"
    subprocess: true
    description: "Create PR"
