customCommands:
  - key: "<c-a>"
    context: "commits"
    command: "gh run list --commit {{.SelectedLocalCommit.Hash}}"
    stream: true
    description: "Show commit's gh workflow run"
  - key: "<c-a>"
    context: "global"
    command: "gh run list"
    description: "Show gh workflow run"
    stream: true
  - key: "<c-t>"
    context: "global"
    command: "git push --tags"
    description: "Push tags"
    stream: true
