shell = "sh -c '{}'"

[[item]]
file='$XDG_CONFIG_HOME/alacritty/colors.yml'
template='alacritty'
rewrite=true

[[item]]
file='~/.Xresources'
template='xresources'
subtemplate='default-256'
rewrite=true
hook='xrdb ~/.Xresources'

[[item]]
file='$XDG_CONFIG_HOME/qutebrowser/colors.py'
template='qutebrowser'
subtemplate='minimal'
rewrite=true
hook='pgrep -x qutebrowser && qutebrowser :config-source'

[[item]]
file='$XDG_CONFIG_HOME/zathura/zathurarc'
template='zathura'

[[item]]
file='$XDG_CONFIG_HOME/dunst/dunstrc'
template='dunst'
subtemplate='background'
hook='killall dunst'

[[item]]
file='$XDG_CONFIG_HOME/polybar/colors.ini'
template='polybar'
hook='polybar-msg cmd restart'
rewrite=true

[[item]]
file='$XDG_CONFIG_HOME/bspwm/bspwm_colors.sh'
template='bspwm'
hook='$XDG_CONFIG_HOME/bspwm/bspwm_colors.sh'
rewrite=true

[[item]]
file='$XDG_CONFIG_HOME/rofi/themes/colors/colors.rasi'
template='rofi'
subtemplate='colors'
rewrite=true

[[item]]
file='$XDG_CONFIG_HOME/vimiv/styles/base16'
template='vimiv'
rewrite=true

[[item]]
file='$XDG_CONFIG_HOME/nvim/lua/plugins/nvim-base16-colors.lua'
template='luakit'
subtemplate='colors'
rewrite=true
