# Makefile to install the packages.

lf:
	yay -S lf-git vidir dragon-drag-and-drop
	sudo pacman -S xclip

polybar:
	yay -S rofi-bluetooth-git polybar-git

sxhkd:
	yay -S rofi-bluetooth-git rofi-greenclip greenclip sxhkd-git
	sudo pacman -S libpulse rofi

sxiv:
	sudo pacman -S imagemagick sxiv sxiv-rifle perl-image-exiftool

vim:
	sudo pacman -S neovim
	yay -S fzf-git

rofi:
	sudo pacman -S rofi
	yay -S rofi-bluetooth-git rofi-greenclip rofi-emoji rofi-dmenu

.PHONY: lf polybar sxhkd sxiv vim rofi
