#!/bin/sh

#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|

# refresh bspc rules
bspc rule -r "*"

bspc monitor HDMI-0 -d 0
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

bspc config border_width 1
bspc config window_gap 8

bspc config -m $BAR_MONITOR top_padding $BAR_HEIGHT
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config single_monocle true
# Set the colors
~/.config/bspwm/bspwm_colors.sh &

# Dropdown terminal
bspc rule -a float state=floating
bspc rule -a \*:float state=floating
bspc rule -a \*:\*:float state=floating
bspc rule -a dropdown sticky=on state=floating hidden=on
bspc rule -a Rofi state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Sxiv:float state=floating
bspc rule -a Dragon-drag-and-drop:\* sticky=on
