#!/bin/sh
#
# Switch to dekstop or switch to last dekstop if already on it.

get_current_desktop () {
    bspc query --desktop focused --desktops --names
}

[ "$1" == $(get_current_desktop) ] && bspc desktop -f last || bspc desktop -f $1
