
[font]
size = 10.0

[font.offset]
x = -1
y = -4

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.95

[window.padding]
x = 2
y = 2
[general]
live_config_reload = true
import = ["colors.toml"]
